ALTER TABLE fivekmrun.Results
DROP foreign key FK_RaceId_ibfk_1;

ALTER TABLE fivekmrun.Results
ADD CONSTRAINT FK_RaceId_ibfk_1
FOREIGN KEY (RaceId) REFERENCES Race(Id)
ON UPDATE CASCADE
ON DELETE NO ACTION;

ALTER TABLE fivekmrun.Race 
MODIFY COLUMN Id int NOT NULL AUTO_INCREMENT;

ALTER TABLE fivekmrun.Race
ADD CONSTRAINT FK_DomParkId_ibfk_2
FOREIGN KEY (DomParkId) REFERENCES DomPark(Id)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE fivekmrun.DomPark 
MODIFY COLUMN id int NOT NULL AUTO_INCREMENT;

ALTER TABLE fivekmrun.Runner
ADD CONSTRAINT FK_CityId_ibfk_2
FOREIGN KEY (DomParkId) REFERENCES City(Id)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE fivekmrun.City 
MODIFY COLUMN id int NOT NULL AUTO_INCREMENT;

ALTER TABLE fivekmrun.Race
ADD COLUMN EventId int;

ALTER TABLE fivekmrun.Race
ADD COLUMN RaceDate datetime;

ALTER TABLE fivekmrun.Results
ADD COLUMN AgePercent float;